name: ETH Trading Bot

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışsın
  workflow_dispatch:     # Manuel çalıştırma

jobs:
  trade:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run Trading Bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
      run: python eth_trading_bot.py
